// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Aqueduct.Appia.Host.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ExportAsHtmlFeature : Xunit.IUseFixture<ExportAsHtmlFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HtmlExporter.feature"
#line hidden
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Export as html", "As a Front end developer\nI want to create a flat representation of my work\nSo I c" +
                    "an submit it to the client or send it to my fellow backend developers", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public virtual void SetFixture(ExportAsHtmlFeature.FixtureData fixtureData)
        {
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Export as html")]
        [Xunit.TraitAttribute("Description", "Create export folder")]
        public virtual void CreateExportFolder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create export folder", new string[] {
                        "init"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("a new HtmlExporter");
#line 9
 testRunner.When("I initialise the exporter");
#line 10
 testRunner.Then("an export folder is created");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Export as html")]
        [Xunit.TraitAttribute("Description", "Delete export foldre if already exists")]
        public virtual void DeleteExportFoldreIfAlreadyExists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete export foldre if already exists", new string[] {
                        "init"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("a new HtmlExporter");
#line 15
 testRunner.And("I have an export folder already containing 2 files");
#line 16
 testRunner.When("I initialise the exporter");
#line 17
 testRunner.Then("a new empty export folder is created in place of the old one");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Export as html")]
        [Xunit.TraitAttribute("Description", "Export all pages")]
        public virtual void ExportAllPages()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Export all pages", new string[] {
                        "export"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("a new HtmlExporter");
#line 22
 testRunner.And("I have 4 cshtml files in the pages folder");
#line 23
 testRunner.When("I export");
#line 24
 testRunner.Then("I have 4 html files in the export directory");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Export as html")]
        [Xunit.TraitAttribute("Description", "Export layouts")]
        public virtual void ExportLayouts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Export layouts", new string[] {
                        "export"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("a new HtmlExporter");
#line 29
 testRunner.And("I have page \"page_with_layout.cshtml\"");
#line 30
 testRunner.And("it uses layout \"layout.cshtml\"");
#line 31
 testRunner.When("I export");
#line 32
 testRunner.Then("I have html page \"page_with_layout.html\"");
#line 33
 testRunner.And("\"page_with_layout.html\" contains html content from layout \"layout.cshtml\"");
#line 34
 testRunner.And("\"page_with_layout.html\" contains html content from page \"page_with_layout.cshtml\"" +
                    "");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Export as html")]
        [Xunit.TraitAttribute("Description", "Export partials")]
        public virtual void ExportPartials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Export partials", new string[] {
                        "export"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("a new HtmlExporter");
#line 39
 testRunner.And("I have page \"page_with_partial.cshtml\"");
#line 40
 testRunner.And("it uses partial \"partial.cshtml\"");
#line 41
 testRunner.When("I export");
#line 42
 testRunner.Then("\"page_with_partial.html\" contains html content from partial \"partial.cshtml\"");
#line 43
 testRunner.And("\"page_with_partial.html\" contains html content from page \"page_with_partial.cshtm" +
                    "l\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Export as html")]
        [Xunit.TraitAttribute("Description", "Copy static files")]
        public virtual void CopyStaticFiles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Copy static files", new string[] {
                        "export"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("a new HtmlExporter");
#line 49
 testRunner.And("I have css folder with 3 files");
#line 50
 testRunner.And("I have js folder with 3 files");
#line 51
 testRunner.When("I export");
#line 52
 testRunner.Then("I have css folder with 3 files in the export folder");
#line 53
 testRunner.And("I have js folder with 3 files in the export folder");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Export as html")]
        [Xunit.TraitAttribute("Description", "Copy static file from root")]
        public virtual void CopyStaticFileFromRoot()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Copy static file from root", new string[] {
                        "export"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("a new HtmlExporter");
#line 58
 testRunner.And("I have static file \"static.txt\"");
#line 59
 testRunner.When("I export");
#line 60
 testRunner.Then("I have file \"static.txt\" in the export folder");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ExportAsHtmlFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ExportAsHtmlFeature.FeatureTearDown();
            }
        }
    }
}
#endregion
